defaults:
  - _self_
  - logger: filesystemlogger
  - override hydra/job_logging: file
  - override hydra/launcher: joblib
  
hydra:
  run:
    dir: outputs/single_run
  sweep:
    dir: outputs/multiruns_joblib
    subdir: .
  job:
    chdir: True


seed: null

algorithm:
  total_steps: 100_000
  log_interval: 10_000
  save_interval: False
  eval_interval: 10_000
  eval_episodes: 100
  video_interval: False
  video_frames: 500

env:
  _target_: utils.envs.make_env
  name : ???
  time_limit : ???
  clear_info: False
  observe_id: False
  standardise_rewards: False
  wrappers : null
